<a href="https://colab.research.google.com/github/kotiang54/AndeLabs/blob/master/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.6.0'

### Importing the libraries

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [5]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 101)

In [9]:
X_train.shape

(7654, 4)

In [10]:
X_test.shape

(1914, 4)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [13]:
ann = Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(Dense(6, activation = 'relu'))

### Adding the second hidden layer

In [15]:
ann.add(Dense(6, activation = 'relu'))

### Adding the output layer

In [16]:
ann.add(Dense(1))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer= 'adam', loss = 'mse')

### Training the ANN model on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size= 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 150008.6562
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 814.4128
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 507.3387
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 493.1435
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 475.9111
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 456.2829
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 434.7735
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 410.7506
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 385.8140
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 358.7308
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 330.6146
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

### Predicting the results of the Test set

In [19]:
y_pred = ann.predict(X_test)

In [20]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis=1))


[[473.94 466.52]
 [465.94 461.73]
 [453.4  450.73]
 ...
 [452.55 458.07]
 [436.47 432.66]
 [432.75 430.55]]


In [22]:
losses = pd.DataFrame(ann.history.history)


In [23]:
losses

Empty DataFrame
Columns: []
Index: []